// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrROSlXvAFs1kebDzwizScL2DYGCKT36E',
    appId: '1:881010663797:web:10ba245e23ab63cb9b733c',
    messagingSenderId: '881010663797',
    projectId: 'librarymanagementapp-b933e',
    authDomain: 'librarymanagementapp-b933e.firebaseapp.com',
    storageBucket: 'librarymanagementapp-b933e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_WT474UpmpVB-vhO61Mk-eNwRRWQDKU',
    appId: '1:881010663797:android:18ec18a7430fbc349b733c',
    messagingSenderId: '881010663797',
    projectId: 'librarymanagementapp-b933e',
    storageBucket: 'librarymanagementapp-b933e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA94StcdAbFYnSK4lIF_cxw7qePyRxlP7o',
    appId: '1:881010663797:ios:b90d5f714e63e7f79b733c',
    messagingSenderId: '881010663797',
    projectId: 'librarymanagementapp-b933e',
    storageBucket: 'librarymanagementapp-b933e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA94StcdAbFYnSK4lIF_cxw7qePyRxlP7o',
    appId: '1:881010663797:ios:b90d5f714e63e7f79b733c',
    messagingSenderId: '881010663797',
    projectId: 'librarymanagementapp-b933e',
    storageBucket: 'librarymanagementapp-b933e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrROSlXvAFs1kebDzwizScL2DYGCKT36E',
    appId: '1:881010663797:web:511d8516671c34299b733c',
    messagingSenderId: '881010663797',
    projectId: 'librarymanagementapp-b933e',
    authDomain: 'librarymanagementapp-b933e.firebaseapp.com',
    storageBucket: 'librarymanagementapp-b933e.firebasestorage.app',
  );

}